name: Compilar Tweak iOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar o ambiente Theos
      run: |
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
        echo "THEOS=/Users/runner/theos" >> $GITHUB_ENV

    - name: Baixar SDK do iOS
      run: |
        git clone https://github.com/theos/sdks.git /Users/runner/theos/sdks
        
    - name: Compilar o Projeto
      run: |
        export THEOS=/Users/runner/theos
        make package FINALPACKAGE=1

    - name: Mover a dylib para download
      run: |
        mkdir output
        cp .theos/obj/debug/FlorkMacro.dylib output/ || cp .theos/obj/FlorkMacro.dylib output/

    - name: Disponibilizar arquivo para Baixar
      uses: actions/upload-artifact@v3
      with:
        name: FlorkMacro-Dylib
        path: output/
